export const navigationItems = [
  {
    label: "My Assistants",
    href: "/dashboard",
    glyph: "AI",
    description: "Manage assistants, status, publishing, and performance.",
    group: "Workspace",
  },
  {
    label: "Knowledge Base",
    href: "/knowledge",
    glyph: "KB",
    description: "Upload, train, and maintain assistant knowledge.",
    group: "Knowledge",
  },
  {
    label: "Chatbot",
    href: "/chatbot",
    glyph: "CB",
    description: "Test responses, citations, confidence, and latency.",
    group: "Assistants",
  },
  {
    label: "Widgets",
    href: "/widgets",
    glyph: "WG",
    description: "Configure, preview, publish, and embed widgets.",
    group: "Deployment",
  },
  {
    label: "Analytics",
    href: "/analytics",
    glyph: "AN",
    description: "Monitor usage, quality, latency, and coverage.",
    group: "Insights",
  },
  {
    label: "Conversations",
    href: "/conversations",
    glyph: "CV",
    description: "Review customer conversations and outcomes.",
    group: "Insights",
  },
  {
    label: "Knowledge Gaps",
    href: "/review/unanswered",
    glyph: "KG",
    description: "Triage unanswered, fallback, and low-confidence replies.",
    group: "Quality",
  },
  {
    label: "Users",
    href: "/users",
    glyph: "US",
    description: "Manage members, roles, and permissions.",
    group: "Admin",
  },
  {
    label: "Settings",
    href: "/settings",
    glyph: "ST",
    description: "Workspace, security, branding, and advanced settings.",
    group: "Admin",
  },
  {
    label: "Billing",
    href: "/billing",
    glyph: "BI",
    description: "Manage plan, trial, usage limits, and invoices.",
    group: "Admin",
  },
] as const;
