from dataclasses import dataclass
from os import getenv


def _get_int(name: str, default: int) -> int:
    raw_value = getenv(name)
    if raw_value is None:
        return default
    return int(raw_value)


@dataclass(frozen=True)
class Settings:
    PROJECT_NAME: str = getenv("PROJECT_NAME", "ChatBotWeb / Yoranix AI Platform")
    PROJECT_DESCRIPTION: str = getenv(
        "PROJECT_DESCRIPTION",
        "Multi-tenant AI knowledge platform API",
    )
    VERSION: str = getenv("VERSION", "0.1.0")
    PHASE: str = getenv("PHASE", "mvp-foundation")
    SERVICE_NAME: str = getenv("SERVICE_NAME", "chatbotweb-api")
    API_V1_PREFIX: str = getenv("API_V1_PREFIX", "/api/v1")
    DATABASE_URL: str = getenv("DATABASE_URL", "sqlite:///./local.db")
    REDIS_URL: str = getenv("REDIS_URL", "redis://localhost:6379/0")
    RATE_LIMIT_IDENTITY_SECRET: str = getenv("RATE_LIMIT_IDENTITY_SECRET", "dev-rate-limit-identity-secret-change-me")
    RATE_LIMIT_REDIS_PREFIX: str = getenv("RATE_LIMIT_REDIS_PREFIX", "rate")
    RATE_LIMIT_REDIS_TIMEOUT_SECONDS: float = float(getenv("RATE_LIMIT_REDIS_TIMEOUT_SECONDS", "0.2"))
    RATE_LIMIT_LOCAL_FALLBACK_ENABLED: bool = getenv("RATE_LIMIT_LOCAL_FALLBACK_ENABLED", "false").lower() in {"1", "true", "yes"}
    PUBLIC_SESSION_TOKEN_HASH_SECRET: str = getenv("PUBLIC_SESSION_TOKEN_HASH_SECRET", "dev-public-session-token-secret-change-me")
    PUBLIC_SESSION_TOKEN_VERSION: str = getenv("PUBLIC_SESSION_TOKEN_VERSION", "v1")
    PUBLIC_SESSION_TOKEN_ID_BYTES: int = _get_int("PUBLIC_SESSION_TOKEN_ID_BYTES", 16)
    PUBLIC_SESSION_SECRET_BYTES: int = _get_int("PUBLIC_SESSION_SECRET_BYTES", 32)
    TRUSTED_PROXY_NETWORKS: str = getenv("TRUSTED_PROXY_NETWORKS", "")
    PUBLIC_WIDGET_ASSET_BASE_URL: str = getenv("PUBLIC_WIDGET_ASSET_BASE_URL", "")
    PUBLIC_MESSAGE_IDEMPOTENCY_HASH_SECRET: str = getenv("PUBLIC_MESSAGE_IDEMPOTENCY_HASH_SECRET", "dev-public-message-idempotency-secret-change-me")
    PUBLIC_MESSAGE_IDEMPOTENCY_TTL_SECONDS: int = _get_int("PUBLIC_MESSAGE_IDEMPOTENCY_TTL_SECONDS", 86400)
    PUBLIC_MESSAGE_IDEMPOTENCY_KEY_MIN_LENGTH: int = _get_int("PUBLIC_MESSAGE_IDEMPOTENCY_KEY_MIN_LENGTH", 16)
    PUBLIC_MESSAGE_IDEMPOTENCY_KEY_MAX_LENGTH: int = _get_int("PUBLIC_MESSAGE_IDEMPOTENCY_KEY_MAX_LENGTH", 160)
    PUBLIC_MESSAGE_MAX_CHARACTERS: int = _get_int("PUBLIC_MESSAGE_MAX_CHARACTERS", 4000)
    PUBLIC_MESSAGE_MAX_BYTES: int = _get_int("PUBLIC_MESSAGE_MAX_BYTES", 12288)
    PUBLIC_MESSAGE_METADATA_MAX_ITEMS: int = _get_int("PUBLIC_MESSAGE_METADATA_MAX_ITEMS", 10)
    PUBLIC_MESSAGE_METADATA_KEY_MAX_LENGTH: int = _get_int("PUBLIC_MESSAGE_METADATA_KEY_MAX_LENGTH", 60)
    PUBLIC_MESSAGE_METADATA_VALUE_MAX_LENGTH: int = _get_int("PUBLIC_MESSAGE_METADATA_VALUE_MAX_LENGTH", 240)
    PUBLIC_MESSAGE_DAILY_COST_QUOTA: str = getenv("PUBLIC_MESSAGE_DAILY_COST_QUOTA", "")
    PUBLIC_MESSAGE_DAILY_TOKEN_QUOTA: int = _get_int("PUBLIC_MESSAGE_DAILY_TOKEN_QUOTA", 0)
    PUBLIC_MESSAGE_DAILY_MESSAGE_QUOTA: int = _get_int("PUBLIC_MESSAGE_DAILY_MESSAGE_QUOTA", 0)
    PUBLIC_MESSAGE_RESTRICTED_OUTPUT_TOKENS: int = _get_int("PUBLIC_MESSAGE_RESTRICTED_OUTPUT_TOKENS", 250)
    PUBLIC_MESSAGE_RESTRICTED_CONTEXT_CHARACTERS: int = _get_int("PUBLIC_MESSAGE_RESTRICTED_CONTEXT_CHARACTERS", 4000)
    PUBLIC_MESSAGE_RESTRICTED_RETRIEVAL_LIMIT: int = _get_int("PUBLIC_MESSAGE_RESTRICTED_RETRIEVAL_LIMIT", 2)
    PUBLIC_MESSAGE_REPEATED_LOOKBACK_COUNT: int = _get_int("PUBLIC_MESSAGE_REPEATED_LOOKBACK_COUNT", 20)
    PUBLIC_MESSAGE_DEFAULT_MODEL_KEY: str = getenv("PUBLIC_MESSAGE_DEFAULT_MODEL_KEY", getenv("DEFAULT_AI_MODEL_KEY", "mock-grounded-answer"))
    PUBLIC_MESSAGE_MAX_INPUT_TOKENS: int = _get_int("PUBLIC_MESSAGE_MAX_INPUT_TOKENS", 1200)
    LOCAL_UPLOAD_ROOT: str = getenv("LOCAL_UPLOAD_ROOT", "./local_uploads")
    MAX_UPLOAD_BYTES: int = _get_int("MAX_UPLOAD_BYTES", 10 * 1024 * 1024)
    CHUNK_SIZE_WORDS: int = _get_int("CHUNK_SIZE_WORDS", 300)
    CHUNK_OVERLAP_WORDS: int = _get_int("CHUNK_OVERLAP_WORDS", 50)
    EMBEDDING_PROVIDER: str = getenv("EMBEDDING_PROVIDER", "local-mock")
    EMBEDDING_MODEL: str = getenv("EMBEDDING_MODEL", "local-mock-v1")
    EMBEDDING_DIMENSION: int = _get_int("EMBEDDING_DIMENSION", 1536)
    RETRIEVAL_MAX_CONTEXT_CHUNKS: int = _get_int("RETRIEVAL_MAX_CONTEXT_CHUNKS", 10)
    RETRIEVAL_MAX_CONTEXT_CHARS: int = _get_int("RETRIEVAL_MAX_CONTEXT_CHARS", 12000)
    PROMPT_VERSION: str = getenv("PROMPT_VERSION", "grounded-answer-v1")
    DEFAULT_AI_PROVIDER_KEY: str = getenv("DEFAULT_AI_PROVIDER_KEY", "mock")
    DEFAULT_AI_MODEL_KEY: str = getenv("DEFAULT_AI_MODEL_KEY", "mock-grounded-answer")
    AI_REQUEST_TIMEOUT_SECONDS: float = float(getenv("AI_REQUEST_TIMEOUT_SECONDS", "30"))
    MOCK_PROVIDER_FAILURE_MODE: str = getenv("MOCK_PROVIDER_FAILURE_MODE", "disabled")
    PUBLIC_WIDGETS_ENABLED: str = getenv("PUBLIC_WIDGETS_ENABLED", "true")
    PUBLIC_WIDGET_MESSAGES_ENABLED: str = getenv("PUBLIC_WIDGET_MESSAGES_ENABLED", "true")
    PUBLIC_WIDGET_PILOT_ENFORCEMENT_ENABLED: str = getenv("PUBLIC_WIDGET_PILOT_ENFORCEMENT_ENABLED", "false")
    PUBLIC_WIDGET_PILOT_ALLOWLIST: str = getenv("PUBLIC_WIDGET_PILOT_ALLOWLIST", "")
    PUBLIC_WIDGET_DISABLED_WIDGETS: str = getenv("PUBLIC_WIDGET_DISABLED_WIDGETS", "")


settings = Settings()
